### ISSUE TITLE
API Connect Plug-in will not install

### ISSUE THREAD

**Issue by vasanthjadav** [IBM-UrbanCode/IBM-API-Connect-UCD#2]
@nhmathis  can you  pls 
[apiconnect-5.898105.zip](https://github.com/IBM-UrbanCode/IBM-API-Connect-UCD/files/1304805/apiconnect-5.898105.zip)
answer below question
https://developer.ibm.com/answers/questions/401078/getting-an-error-for-customize-apic-plugin-ucd.html

**Comment by nhmathis** [comment]
Original question: 
Hello,

I am trying to add scope and space info plug-in and tried to deploy/update, but i am getting an error

Please find the custom zip file and let me know what I am missing.

Error:- Error loading plugin, The file plugin.xml was not found within the root directory of the zip file


Cause of Error:
I suspect the plugin distributable is not correctly built. This could have occurred in one of two ways:
1) The zip file was extracted and rezipped and now the `plugin.xml` file is no longer in the root directory.
2) The GitHub repository was downloaded as a zip. 

If you extract the .zip file, is the `plugin.xml` in the root/base directory of the zip. The error indicates that it is not.

Solution:
To fix, simply download the plugin again from our microsite and reinstall: https://developer.ibm.com/urbancode/plugin/ibm-api-connect/ All plugins downloaded from the website have been validated.
