### ISSUE TITLE
No ability to specify space in product publish

### ISSUE THREAD

**Issue by dmcorboy** [IBM-UrbanCode/IBM-API-Connect-UCD#4]
When utilising the 'spaces' feature of API Connect https://www.ibm.com/support/knowledgecenter/SSMNED_5.0.0/com.ibm.apic.apionprem.doc/tapic_syndication_spaces_configure.html you are given the option to deploy a product to a space within a catalog. This feature is currently not supported by the Publish API Product Definitions Step

**Comment by dmcorboy** [comment]
I have been able to utilise this code successfully on our instance of UCD https://github.com/IBM-UrbanCode/IBM-API-Connect-UCD/pull/5

**Comment by nhmathis** [comment]
Thank you! Will release the plugin by the end of the day.

**Comment by dmcorboy** [comment]
Any word on getting this out the door? I would prefer to use the published plugin for our platform.

**Comment by nhmathis** [comment]
Sorry for the delay! It's released: https://developer.ibm.com/urbancode/plugin/ibm-api-connect/
